import type { Metadata } from "next";
import "./css/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="max-w-2xl mx-auto p-4">
        <header className="mb-4">
          <h1 className="text-2xl font-bold">My Blog</h1>
          <nav className="space-x-4">
            <a href="/">Home</a>
            <a href="/posts">Posts</a>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
